version: '3.1'

services:
  
  mongodb:
      image: mongo:latest
      volumes:
       - ./data:/data/db
      ports:
       - "27017:27017"
       
  grafana:
      image: grafana/grafana
      ports:
        - 3000:3000
      volumes:
        - grafana_data:/var/lib/grafana
volumes:
  grafana_data: